const followers  = [
    {
    login: "ArefMq",
    id: 10897992,
    node_id: "MDQ6VXNlcjEwODk3OTky",
    avatar_url: "https://avatars.githubusercontent.com/u/10897992?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ArefMq",
    html_url: "https://github.com/ArefMq",
    followers_url: "https://api.github.com/users/ArefMq/followers",
    following_url: "https://api.github.com/users/ArefMq/following{/other_user}",
    gists_url: "https://api.github.com/users/ArefMq/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ArefMq/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ArefMq/subscriptions",
    organizations_url: "https://api.github.com/users/ArefMq/orgs",
    repos_url: "https://api.github.com/users/ArefMq/repos",
    events_url: "https://api.github.com/users/ArefMq/events{/privacy}",
    received_events_url: "https://api.github.com/users/ArefMq/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "MafujShikder",
    id: 34533694,
    node_id: "MDQ6VXNlcjM0NTMzNjk0",
    avatar_url: "https://avatars.githubusercontent.com/u/34533694?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MafujShikder",
    html_url: "https://github.com/MafujShikder",
    followers_url: "https://api.github.com/users/MafujShikder/followers",
    following_url: "https://api.github.com/users/MafujShikder/following{/other_user}",
    gists_url: "https://api.github.com/users/MafujShikder/gists{/gist_id}",
    starred_url: "https://api.github.com/users/MafujShikder/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/MafujShikder/subscriptions",
    organizations_url: "https://api.github.com/users/MafujShikder/orgs",
    repos_url: "https://api.github.com/users/MafujShikder/repos",
    events_url: "https://api.github.com/users/MafujShikder/events{/privacy}",
    received_events_url: "https://api.github.com/users/MafujShikder/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "Ux-beast",
    id: 49905714,
    node_id: "MDQ6VXNlcjQ5OTA1NzE0",
    avatar_url: "https://avatars.githubusercontent.com/u/49905714?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ux-beast",
    html_url: "https://github.com/Ux-beast",
    followers_url: "https://api.github.com/users/Ux-beast/followers",
    following_url: "https://api.github.com/users/Ux-beast/following{/other_user}",
    gists_url: "https://api.github.com/users/Ux-beast/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Ux-beast/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Ux-beast/subscriptions",
    organizations_url: "https://api.github.com/users/Ux-beast/orgs",
    repos_url: "https://api.github.com/users/Ux-beast/repos",
    events_url: "https://api.github.com/users/Ux-beast/events{/privacy}",
    received_events_url: "https://api.github.com/users/Ux-beast/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "Niyonsengaeric",
    id: 50768983,
    node_id: "MDQ6VXNlcjUwNzY4OTgz",
    avatar_url: "https://avatars.githubusercontent.com/u/50768983?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Niyonsengaeric",
    html_url: "https://github.com/Niyonsengaeric",
    followers_url: "https://api.github.com/users/Niyonsengaeric/followers",
    following_url: "https://api.github.com/users/Niyonsengaeric/following{/other_user}",
    gists_url: "https://api.github.com/users/Niyonsengaeric/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Niyonsengaeric/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Niyonsengaeric/subscriptions",
    organizations_url: "https://api.github.com/users/Niyonsengaeric/orgs",
    repos_url: "https://api.github.com/users/Niyonsengaeric/repos",
    events_url: "https://api.github.com/users/Niyonsengaeric/events{/privacy}",
    received_events_url: "https://api.github.com/users/Niyonsengaeric/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "hakoemmy",
    id: 51243858,
    node_id: "MDQ6VXNlcjUxMjQzODU4",
    avatar_url: "https://avatars.githubusercontent.com/u/51243858?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hakoemmy",
    html_url: "https://github.com/hakoemmy",
    followers_url: "https://api.github.com/users/hakoemmy/followers",
    following_url: "https://api.github.com/users/hakoemmy/following{/other_user}",
    gists_url: "https://api.github.com/users/hakoemmy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/hakoemmy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hakoemmy/subscriptions",
    organizations_url: "https://api.github.com/users/hakoemmy/orgs",
    repos_url: "https://api.github.com/users/hakoemmy/repos",
    events_url: "https://api.github.com/users/hakoemmy/events{/privacy}",
    received_events_url: "https://api.github.com/users/hakoemmy/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "IRSAGE",
    id: 53136152,
    node_id: "MDQ6VXNlcjUzMTM2MTUy",
    avatar_url: "https://avatars.githubusercontent.com/u/53136152?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/IRSAGE",
    html_url: "https://github.com/IRSAGE",
    followers_url: "https://api.github.com/users/IRSAGE/followers",
    following_url: "https://api.github.com/users/IRSAGE/following{/other_user}",
    gists_url: "https://api.github.com/users/IRSAGE/gists{/gist_id}",
    starred_url: "https://api.github.com/users/IRSAGE/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/IRSAGE/subscriptions",
    organizations_url: "https://api.github.com/users/IRSAGE/orgs",
    repos_url: "https://api.github.com/users/IRSAGE/repos",
    events_url: "https://api.github.com/users/IRSAGE/events{/privacy}",
    received_events_url: "https://api.github.com/users/IRSAGE/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "manzi-guev",
    id: 53451069,
    node_id: "MDQ6VXNlcjUzNDUxMDY5",
    avatar_url: "https://avatars.githubusercontent.com/u/53451069?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/manzi-guev",
    html_url: "https://github.com/manzi-guev",
    followers_url: "https://api.github.com/users/manzi-guev/followers",
    following_url: "https://api.github.com/users/manzi-guev/following{/other_user}",
    gists_url: "https://api.github.com/users/manzi-guev/gists{/gist_id}",
    starred_url: "https://api.github.com/users/manzi-guev/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/manzi-guev/subscriptions",
    organizations_url: "https://api.github.com/users/manzi-guev/orgs",
    repos_url: "https://api.github.com/users/manzi-guev/repos",
    events_url: "https://api.github.com/users/manzi-guev/events{/privacy}",
    received_events_url: "https://api.github.com/users/manzi-guev/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "Hodal66",
    id: 85940364,
    node_id: "MDQ6VXNlcjg1OTQwMzY0",
    avatar_url: "https://avatars.githubusercontent.com/u/85940364?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Hodal66",
    html_url: "https://github.com/Hodal66",
    followers_url: "https://api.github.com/users/Hodal66/followers",
    following_url: "https://api.github.com/users/Hodal66/following{/other_user}",
    gists_url: "https://api.github.com/users/Hodal66/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Hodal66/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Hodal66/subscriptions",
    organizations_url: "https://api.github.com/users/Hodal66/orgs",
    repos_url: "https://api.github.com/users/Hodal66/repos",
    events_url: "https://api.github.com/users/Hodal66/events{/privacy}",
    received_events_url: "https://api.github.com/users/Hodal66/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "Techiesourcer",
    id: 87067046,
    node_id: "MDQ6VXNlcjg3MDY3MDQ2",
    avatar_url: "https://avatars.githubusercontent.com/u/87067046?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Techiesourcer",
    html_url: "https://github.com/Techiesourcer",
    followers_url: "https://api.github.com/users/Techiesourcer/followers",
    following_url: "https://api.github.com/users/Techiesourcer/following{/other_user}",
    gists_url: "https://api.github.com/users/Techiesourcer/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Techiesourcer/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Techiesourcer/subscriptions",
    organizations_url: "https://api.github.com/users/Techiesourcer/orgs",
    repos_url: "https://api.github.com/users/Techiesourcer/repos",
    events_url: "https://api.github.com/users/Techiesourcer/events{/privacy}",
    received_events_url: "https://api.github.com/users/Techiesourcer/received_events",
    type: "User",
    site_admin: false
    }
    ];

    export default followers;