import followers from "./followersMockData";

const following = [
    {
    login: "ComBarnea",
    id: 8877285,
    node_id: "MDQ6VXNlcjg4NzcyODU=",
    avatar_url: "https://avatars.githubusercontent.com/u/8877285?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ComBarnea",
    html_url: "https://github.com/ComBarnea",
    followers_url: "https://api.github.com/users/ComBarnea/followers",
    following_url: "https://api.github.com/users/ComBarnea/following{/other_user}",
    gists_url: "https://api.github.com/users/ComBarnea/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ComBarnea/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ComBarnea/subscriptions",
    organizations_url: "https://api.github.com/users/ComBarnea/orgs",
    repos_url: "https://api.github.com/users/ComBarnea/repos",
    events_url: "https://api.github.com/users/ComBarnea/events{/privacy}",
    received_events_url: "https://api.github.com/users/ComBarnea/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "MafujShikder",
    id: 34533694,
    node_id: "MDQ6VXNlcjM0NTMzNjk0",
    avatar_url: "https://avatars.githubusercontent.com/u/34533694?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MafujShikder",
    html_url: "https://github.com/MafujShikder",
    followers_url: "https://api.github.com/users/MafujShikder/followers",
    following_url: "https://api.github.com/users/MafujShikder/following{/other_user}",
    gists_url: "https://api.github.com/users/MafujShikder/gists{/gist_id}",
    starred_url: "https://api.github.com/users/MafujShikder/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/MafujShikder/subscriptions",
    organizations_url: "https://api.github.com/users/MafujShikder/orgs",
    repos_url: "https://api.github.com/users/MafujShikder/repos",
    events_url: "https://api.github.com/users/MafujShikder/events{/privacy}",
    received_events_url: "https://api.github.com/users/MafujShikder/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "manzi-guev",
    id: 53451069,
    node_id: "MDQ6VXNlcjUzNDUxMDY5",
    avatar_url: "https://avatars.githubusercontent.com/u/53451069?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/manzi-guev",
    html_url: "https://github.com/manzi-guev",
    followers_url: "https://api.github.com/users/manzi-guev/followers",
    following_url: "https://api.github.com/users/manzi-guev/following{/other_user}",
    gists_url: "https://api.github.com/users/manzi-guev/gists{/gist_id}",
    starred_url: "https://api.github.com/users/manzi-guev/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/manzi-guev/subscriptions",
    organizations_url: "https://api.github.com/users/manzi-guev/orgs",
    repos_url: "https://api.github.com/users/manzi-guev/repos",
    events_url: "https://api.github.com/users/manzi-guev/events{/privacy}",
    received_events_url: "https://api.github.com/users/manzi-guev/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "KKDoddy",
    id: 54485649,
    node_id: "MDQ6VXNlcjU0NDg1NjQ5",
    avatar_url: "https://avatars.githubusercontent.com/u/54485649?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/KKDoddy",
    html_url: "https://github.com/KKDoddy",
    followers_url: "https://api.github.com/users/KKDoddy/followers",
    following_url: "https://api.github.com/users/KKDoddy/following{/other_user}",
    gists_url: "https://api.github.com/users/KKDoddy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/KKDoddy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/KKDoddy/subscriptions",
    organizations_url: "https://api.github.com/users/KKDoddy/orgs",
    repos_url: "https://api.github.com/users/KKDoddy/repos",
    events_url: "https://api.github.com/users/KKDoddy/events{/privacy}",
    received_events_url: "https://api.github.com/users/KKDoddy/received_events",
    type: "User",
    site_admin: false
    }
    ];

    export default followers;