const user =  {
  login: "AbdoulNuru",
  id: 53453380,
  node_id: "MDQ6VXNlcjUzNDUzMzgw",
  avatar_url: "https://avatars.githubusercontent.com/u/53453380?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/AbdoulNuru",
  html_url: "https://github.com/AbdoulNuru",
  followers_url: "https://api.github.com/users/AbdoulNuru/followers",
  following_url: "https://api.github.com/users/AbdoulNuru/following{/other_user}",
  gists_url: "https://api.github.com/users/AbdoulNuru/gists{/gist_id}",
  starred_url: "https://api.github.com/users/AbdoulNuru/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/AbdoulNuru/subscriptions",
  organizations_url: "https://api.github.com/users/AbdoulNuru/orgs",
  repos_url: "https://api.github.com/users/AbdoulNuru/repos",
  events_url: "https://api.github.com/users/AbdoulNuru/events{/privacy}",
  received_events_url: "https://api.github.com/users/AbdoulNuru/received_events",
  type: "User",
  site_admin: false,
  name: "Abdoul Nuru",
  company: "@ruubik",
  blog: "https://abdoulnuru.github.io/portfolio/",
  location: "Kigali, Rwanda",
  email: null,
  hireable: true,
  bio: "Fullstack Software Engineer || React js, Typescript, NodeJs, NestJs, Spring boot.",
  twitter_username: "nuru_abdoul",
  public_repos: 33,
  public_gists: 0,
  followers: 9,
  following: 4,
  created_at: "2019-07-29T23:10:02Z",
  updated_at: "2022-06-09T20:02:06Z"
  };

  export default user;